Applications/RailsApp/config/routes.rb
FlixelLights::Application.routes.draw do

  get "smart_story/:story_id/composer/:page_number", :to => "smart_story#composer", 
  :as => "smart_story_composer"
  
  namespace :smart_story do
    get "new_story"
    get "register"
    get "echo"
    put "echo"
  end

  resources :story_pages

  resources :story_texts

  resources :story_images

  resources :stories do 
    member do 
      get :ipad_output
    end
  end

  resources :mappers

  resources :tasks

  resources :commands

  resources :tags 
  

  resource :composer, only: :index do
    get "/", :to =>  "composer#index"
    
    collection do 
      get "library_selector", :to => "composer#library_selector"
    end
  end

  get "composer/test"

  namespace :study do
      get "index"
      get "info"
      get "task"
      post "save_info"
  end
  resources :library do
    collection do
      get "/", :to => "behaviors#index"
    end
  end
     
  devise_for :users

  resources :flavors

  resources :actuations

  resources :experiments

  resources :actuators

  root "application#index", :as => "home"

  
  get "light/view"
  get "light/wave"
  get "light/lb"
  get "light/index"
  get "light/synthesize"
  get "light/sequence"
  get "light/blinkm"
  post "light/create"

  get "behaviors/index"
  get "behaviors/new_stack"
  get "behaviors/new_wave"
  get "behaviors/record_wave"
  get "behaviors/get_states"
  post "behaviors/json_to_cpp"
  post "behaviors/create"
  resources :behaviors

  scope '/api' do

    resources :actuators, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do 
        get "flavors"
      end
    end
    resources :behaviors, :defaults => { :format => 'json'} do
      get 'sparse'
      collection do
        post 'scanner'
      end
    end
    resources :flavors, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do
        get "behaviors"
        get "tags"
      end
    end 
    resources :tags, :defaults => { :format => 'json'} do
        collection do 
          get 'behaviors' 
        end
    end
    namespace :tasks, :defaults => { :format => 'json'}  do
        get 'schedule', :path => "/:id/schedule"
    end
  end

  post "sequences/json_to_cpp"
  post "sequences/create"
  resources :sequences

  post "schemes/create"
  resources :schemes

end

Applications/RailsApp/app/models/story_text.rb
class StoryText < ActiveRecord::Base
	belongs_to :story_page
end

Applications/RailsApp/app/controllers/story_texts_controller.rb
class StoryTextsController < ApplicationController
  before_action :set_story_text, only: [:show, :edit, :update, :destroy]

  # GET /story_texts
  # GET /story_texts.json
  def index
    @story_texts = StoryText.all
  end



  # GET /story_texts/1
  # GET /story_texts/1.json
  def show
  end

  # GET /story_texts/new
  def new
    @story_text = StoryText.new
  end

  # GET /story_texts/1/edit
  def edit
  end

  # POST /story_texts
  # POST /story_texts.json
  def create
    @story_text = StoryText.new(story_text_params)

    respond_to do |format|
      if @story_text.save
        format.html { redirect_to @story_text, notice: 'Story text was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story_text }
      else
        format.html { render action: 'new' }
        format.json { render json: @story_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_texts/1
  # PATCH/PUT /story_texts/1.json
  def update
    respond_to do |format|
      if @story_text.update(story_text_params)
        format.html { redirect_to @story_text, notice: 'Story text was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story_text.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_texts/1
  # DELETE /story_texts/1.json
  def destroy
    @story_text.destroy
    respond_to do |format|
      format.html { redirect_to story_texts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_text
      @story_text = StoryText.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_text_params
      params.require(:story_text).permit(:text, :fontSize, :center, :textBackgroundHex, :textBackgroundAlpha, :border, :story_page_id)
    end
end

Applications/RailsApp/app/views/story_texts/_form.html.erb
<%= form_for(@story_text) do |f| %>
  <% if @story_text.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_text.errors.count, "error") %> prohibited this story_text from being saved:</h2>

      <ul>
      <% @story_text.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :story_page_id%><br>
    <% f.number_field :story_page_id %>
    <%= select("story_text", "story_page_id", StoryPage.all.collect {|p| 
      [ "#{p.story.title} #{p.page_number}", p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :text %><br>
    <%= f.text_field :text %>
  </div>
  <div class="field">
    <%= f.label :fontSize %><br>
    <%= f.number_field :fontSize %>
  </div>
  <div class="field">
    <%= f.label :center %><br>
    <%= f.text_field :center %>
  </div>
  <div class="field">
    <%= f.label :textBackgroundHex %><br>
    <%= f.text_field :textBackgroundHex %>
  </div>
  <div class="field">
    <%= f.label :textBackgroundAlpha %><br>
    <%= f.text_field :textBackgroundAlpha %>
  </div>
  <div class="field">
    <%= f.label :border %><br>
    <%= f.number_field :border %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Applications/RailsApp/app/views/story_texts/edit.html.erb
<h1>Editing story_text</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_text %> |
<%= link_to 'Back', story_texts_path %>

Applications/RailsApp/app/views/story_texts/index.html.erb
<h1>Listing story_texts</h1>

<table>
  <thead>
    <tr>
      <th>Text</th>
      <th>Fontsize</th>
      <th>Center</th>
      <th>Textbackgroundhex</th>
      <th>Textbackgroundalpha</th>
      <th>Border</th>
      <th>Story</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @story_texts.each do |story_text| %>
      <tr>
        <td><%= "#{story_text.story_page.story.title} #{story_text.story_page.page_number} " %></td>
        <td><%= story_text.text %></td>
        <td><%= story_text.fontSize %></td>
        <td><%= story_text.center %></td>
        <td><%= story_text.textBackgroundHex %></td>
        <td><%= story_text.textBackgroundAlpha %></td>
        <td><%= story_text.border %></td>
         
        <td><%= link_to 'Show', story_text %></td>
        <td><%= link_to 'Edit', edit_story_text_path(story_text) %></td>
        <td><%= link_to 'Destroy', story_text, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story text', new_story_text_path %>

Applications/RailsApp/app/views/story_texts/new.html.erb
<h1>New story_text</h1>

<%= render 'form' %>

<%= link_to 'Back', story_texts_path %>

Applications/RailsApp/app/views/story_texts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Text:</strong>
  <%= @story_text.text %>
</p>

<p>
  <strong>Fontsize:</strong>
  <%= @story_text.fontSize %>
</p>

<p>
  <strong>Center:</strong>
  <%= @story_text.center %>
</p>

<p>
  <strong>Textbackgroundhex:</strong>
  <%= @story_text.textBackgroundHex %>
</p>

<p>
  <strong>Textbackgroundalpha:</strong>
  <%= @story_text.textBackgroundAlpha %>
</p>

<p>
  <strong>Border:</strong>
  <%= @story_text.border %>
</p>

<p>
  <strong>Story:</strong>
    <%= "#{@story_text.story_page.story.title} #{@story_text.story_page.page_number}" %>
</p>

<%= link_to 'Edit', edit_story_text_path(@story_text) %> |
<%= link_to 'Back', story_texts_path %>