Applications/RailsApp/config/routes.rb
FlixelLights::Application.routes.draw do

  get "smart_story/:story_id/composer/:page_number", :to => "smart_story#composer", 
  :as => "smart_story_composer"
  
  namespace :smart_story do
    get "new_story"
    get "register"
    get "echo"
    put "echo"
  end

  resources :story_pages

  resources :story_texts

  resources :story_images

  resources :stories do 
    member do 
      get :ipad_output
    end
  end

  resources :mappers

  resources :tasks

  resources :commands

  resources :tags 
  

  resource :composer, only: :index do
    get "/", :to =>  "composer#index"
    
    collection do 
      get "library_selector", :to => "composer#library_selector"
    end
  end

  get "composer/test"

  namespace :study do
      get "index"
      get "info"
      get "task"
      post "save_info"
  end
  resources :library do
    collection do
      get "/", :to => "behaviors#index"
    end
  end
     
  devise_for :users

  resources :flavors

  resources :actuations

  resources :experiments

  resources :actuators

  root "application#index", :as => "home"

  
  get "light/view"
  get "light/wave"
  get "light/lb"
  get "light/index"
  get "light/synthesize"
  get "light/sequence"
  get "light/blinkm"
  post "light/create"

  get "behaviors/index"
  get "behaviors/new_stack"
  get "behaviors/new_wave"
  get "behaviors/record_wave"
  get "behaviors/get_states"
  post "behaviors/json_to_cpp"
  post "behaviors/create"
  resources :behaviors

  scope '/api' do

    resources :actuators, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do 
        get "flavors"
      end
    end
    resources :behaviors, :defaults => { :format => 'json'} do
      get 'sparse'
      collection do
        post 'scanner'
      end
    end
    resources :flavors, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do
        get "behaviors"
        get "tags"
      end
    end 
    resources :tags, :defaults => { :format => 'json'} do
        collection do 
          get 'behaviors' 
        end
    end
    namespace :tasks, :defaults => { :format => 'json'}  do
        get 'schedule', :path => "/:id/schedule"
    end
  end

  post "sequences/json_to_cpp"
  post "sequences/create"
  resources :sequences

  post "schemes/create"
  resources :schemes

end

Applications/RailsApp/app/models/experiment.rb
class Experiment < ActiveRecord::Base
	belongs_to :actuator
end

Applications/RailsApp/app/controllers/experiments_controller.rb
class ExperimentsController < ApplicationController
  before_action :set_experiment, only: [:show, :edit, :update, :destroy]

  # GET /experiments
  # GET /experiments.json
  def index
    @experiments = Experiment.all
  end

  # GET /experiments/1
  # GET /experiments/1.json
  def show
  end

  # GET /experiments/new
  def new
    @experiment = Experiment.new
  end

  # GET /experiments/1/edit
  def edit
  end

  # POST /experiments
  # POST /experiments.json
  def create
    @experiment = Experiment.new(experiment_params)

    respond_to do |format|
      if @experiment.save
        format.html { redirect_to @experiment, notice: 'Experiment was successfully created.' }
        format.json { render action: 'show', status: :created, location: @experiment }
      else
        format.html { render action: 'new' }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /experiments/1
  # PATCH/PUT /experiments/1.json
  def update
    respond_to do |format|
      if @experiment.update(experiment_params)
        format.html { redirect_to @experiment, notice: 'Experiment was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @experiment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /experiments/1
  # DELETE /experiments/1.json
  def destroy
    @experiment.destroy
    respond_to do |format|
      format.html { redirect_to experiments_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_experiment
      @experiment = Experiment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def experiment_params
      params.require(:experiment).permit(:actuator_id, :physical_mag, :subjective_mag, :stimulus_cond, :continuum)
    end
end

Applications/RailsApp/app/helpers/experiments_helper.rb
module ExperimentsHelper
end

Applications/RailsApp/app/views/experiments/_form.html.erb
<%= form_for(@experiment) do |f| %>
  <% if @experiment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@experiment.errors.count, "error") %> prohibited this experiment from being saved:</h2>

      <ul>
      <% @experiment.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :actuator_id %><br>
    <%= f.text_field :actuator_id %>
  </div>
  <div class="field">
    <%= f.label :physical_mag %><br>
    <%= f.text_field :physical_mag %>
  </div>
  <div class="field">
    <%= f.label :subjective_mag %><br>
    <%= f.text_field :subjective_mag %>
  </div>
  <div class="field">
    <%= f.label :stimulus_cond %><br>
    <%= f.text_field :stimulus_cond %>
  </div>
  <div class="field">
    <%= f.label :continuum %><br>
    <%= f.text_field :continuum %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Applications/RailsApp/app/views/experiments/edit.html.erb
<h1>Editing experiment</h1>

<%= render 'form' %>

<%= link_to 'Show', @experiment %> |
<%= link_to 'Back', experiments_path %>

Applications/RailsApp/app/views/experiments/index.html.erb
<h1>Listing experiments</h1>

<table>
  <thead>
    <tr>
      <th>Actuator</th>
      <th>Physical mag</th>
      <th>Subjective mag</th>
      <th>Stimulus cond</th>
      <th>Continuum</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @experiments.each do |experiment| %>
      <tr>
        <td><%= experiment.actuator_id %></td>
        <td><%= experiment.physical_mag %></td>
        <td><%= experiment.subjective_mag %></td>
        <td><%= experiment.stimulus_cond %></td>
        <td><%= experiment.continuum %></td>
        <td><%= link_to 'Show', experiment %></td>
        <td><%= link_to 'Edit', edit_experiment_path(experiment) %></td>
        <td><%= link_to 'Destroy', experiment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Experiment', new_experiment_path %>

Applications/RailsApp/app/views/experiments/new.html.erb
<h1>New experiment</h1>

<%= render 'form' %>

<%= link_to 'Back', experiments_path %>

Applications/RailsApp/app/views/experiments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Actuator:</strong>
  <%= @experiment.actuator_id %>
</p>

<p>
  <strong>Physical mag:</strong>
  <%= @experiment.physical_mag %>
</p>

<p>
  <strong>Subjective mag:</strong>
  <%= @experiment.subjective_mag %>
</p>

<p>
  <strong>Stimulus cond:</strong>
  <%= @experiment.stimulus_cond %>
</p>

<p>
  <strong>Continuum:</strong>
  <%= @experiment.continuum %>
</p>

<%= link_to 'Edit', edit_experiment_path(@experiment) %> |
<%= link_to 'Back', experiments_path %>