Applications/RailsApp/config/routes.rb
FlixelLights::Application.routes.draw do

  get "smart_story/:story_id/composer/:page_number", :to => "smart_story#composer", 
  :as => "smart_story_composer"
  
  namespace :smart_story do
    get "new_story"
    get "register"
    get "echo"
    put "echo"
  end

  resources :story_pages

  resources :story_texts

  resources :story_images

  resources :stories do 
    member do 
      get :ipad_output
    end
  end

  resources :mappers

  resources :tasks

  resources :commands

  resources :tags 
  

  resource :composer, only: :index do
    get "/", :to =>  "composer#index"
    
    collection do 
      get "library_selector", :to => "composer#library_selector"
    end
  end

  get "composer/test"

  namespace :study do
      get "index"
      get "info"
      get "task"
      post "save_info"
  end
  resources :library do
    collection do
      get "/", :to => "behaviors#index"
    end
  end
     
  devise_for :users

  resources :flavors

  resources :actuations

  resources :experiments

  resources :actuators

  root "application#index", :as => "home"

  
  get "light/view"
  get "light/wave"
  get "light/lb"
  get "light/index"
  get "light/synthesize"
  get "light/sequence"
  get "light/blinkm"
  post "light/create"

  get "behaviors/index"
  get "behaviors/new_stack"
  get "behaviors/new_wave"
  get "behaviors/record_wave"
  get "behaviors/get_states"
  post "behaviors/json_to_cpp"
  post "behaviors/create"
  resources :behaviors

  scope '/api' do

    resources :actuators, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do 
        get "flavors"
      end
    end
    resources :behaviors, :defaults => { :format => 'json'} do
      get 'sparse'
      collection do
        post 'scanner'
      end
    end
    resources :flavors, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do
        get "behaviors"
        get "tags"
      end
    end 
    resources :tags, :defaults => { :format => 'json'} do
        collection do 
          get 'behaviors' 
        end
    end
    namespace :tasks, :defaults => { :format => 'json'}  do
        get 'schedule', :path => "/:id/schedule"
    end
  end

  post "sequences/json_to_cpp"
  post "sequences/create"
  resources :sequences

  post "schemes/create"
  resources :schemes

end

Applications/RailsApp/app/models/story_image.rb
class StoryImage < ActiveRecord::Base
	belongs_to :story_page
	mount_uploader :file, PictureUploader
end

Applications/RailsApp/app/controllers/story_images_controller.rb
class StoryImagesController < ApplicationController
  before_action :set_story_image, only: [:show, :edit, :update, :destroy]

  # GET /story_images
  # GET /story_images.json
  def index
    @story_images = StoryImage.all
  end

  # GET /story_images/1
  # GET /story_images/1.json
  def show
  end

  # GET /story_images/new
  def new
    @story_image = StoryImage.new
  end

  # GET /story_images/1/edit
  def edit
  end

  # POST /story_images
  # POST /story_images.json
  def create
    @story_image = StoryImage.new(story_image_params)

    respond_to do |format|
      if @story_image.save
        format.html { redirect_to @story_image, notice: 'Story image was successfully created.' }
        format.json { render action: 'show', status: :created, location: @story_image }
      else
        format.html { render action: 'new' }
        format.json { render json: @story_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /story_images/1
  # PATCH/PUT /story_images/1.json
  def update
    respond_to do |format|
      if @story_image.update(story_image_params)
        format.html { redirect_to @story_image, notice: 'Story image was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @story_image.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /story_images/1
  # DELETE /story_images/1.json
  def destroy
    @story_image.destroy
    respond_to do |format|
      format.html { redirect_to story_images_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_story_image
      @story_image = StoryImage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def story_image_params
      params.require(:story_image).permit(:file, :size, :story_page_id)
    end
end

Applications/RailsApp/app/views/story_images/_form.html.erb
<%= form_for @story_image,  :html => {:multipart => true} do |f| %>
  <% if @story_image.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@story_image.errors.count, "error") %> prohibited this story_image from being saved:</h2>

      <ul>
      <% @story_image.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :file %><br>
     <%= f.file_field :file %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :story_page_id%><br>
    <% f.number_field :story_page_id %>
    <%= select("story_image", "story_page_id", StoryPage.all.collect {|p| 
      [ "#{p.story.title} #{p.page_number}", p.id ] }) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Applications/RailsApp/app/views/story_images/edit.html.erb
<h1>Editing story_image</h1>

<%= render 'form' %>

<%= link_to 'Show', @story_image %> |
<%= link_to 'Back', story_images_path %>

Applications/RailsApp/app/views/story_images/index.html.erb
<h1>Listing story_images</h1>

<table>
  <thead>
    <tr>
      <th>Story</th>
      <th>File</th>
      <th>Size</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @story_images.each do |story_image| %>
      <tr>
        <td><%= "#{story_image.story_page.story.title} #{story_image.story_page.page_number} " %></td>
        <td><%= image_tag story_image.file_url %></td>
        <td><%= story_image.size %></td>
        
        <td><%= link_to 'Show', story_image %></td>
        <td><%= link_to 'Edit', edit_story_image_path(story_image) %></td>
        <td><%= link_to 'Destroy', story_image, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Story image', new_story_image_path %>

Applications/RailsApp/app/views/story_images/new.html.erb
<h1>New story_image</h1>

<%= render 'form' %>

<%= link_to 'Back', story_images_path %>

Applications/RailsApp/app/views/story_images/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>File:</strong>
  <%= image_tag @story_image.file_url %>
</p>

<p>
  <strong>Size:</strong>
  <%= @story_image.size %>
</p>

<p>
  <strong>Story:</strong>
  <%= "#{@story_image.story_page.story.title} #{@story_image.story_page.page_number}" %>
</p>

<%= link_to 'Edit', edit_story_image_path(@story_image) %> |
<%= link_to 'Back', story_images_path %>