Applications/RailsApp/config/routes.rb
FlixelLights::Application.routes.draw do

  get "smart_story/:story_id/composer/:page_number", :to => "smart_story#composer", 
  :as => "smart_story_composer"
  
  namespace :smart_story do
    get "new_story"
    get "register"
    get "echo"
    put "echo"
  end

  resources :story_pages

  resources :story_texts

  resources :story_images

  resources :stories do 
    member do 
      get :ipad_output
    end
  end

  resources :mappers

  resources :tasks

  resources :commands

  resources :tags 
  

  resource :composer, only: :index do
    get "/", :to =>  "composer#index"
    
    collection do 
      get "library_selector", :to => "composer#library_selector"
    end
  end

  get "composer/test"

  namespace :study do
      get "index"
      get "info"
      get "task"
      post "save_info"
  end
  resources :library do
    collection do
      get "/", :to => "behaviors#index"
    end
  end
     
  devise_for :users

  resources :flavors

  resources :actuations

  resources :experiments

  resources :actuators

  root "application#index", :as => "home"

  
  get "light/view"
  get "light/wave"
  get "light/lb"
  get "light/index"
  get "light/synthesize"
  get "light/sequence"
  get "light/blinkm"
  post "light/create"

  get "behaviors/index"
  get "behaviors/new_stack"
  get "behaviors/new_wave"
  get "behaviors/record_wave"
  get "behaviors/get_states"
  post "behaviors/json_to_cpp"
  post "behaviors/create"
  resources :behaviors

  scope '/api' do

    resources :actuators, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do 
        get "flavors"
      end
    end
    resources :behaviors, :defaults => { :format => 'json'} do
      get 'sparse'
      collection do
        post 'scanner'
      end
    end
    resources :flavors, :defaults => { :format => 'json'} do
      collection do 
        get "counts"
      end
      member do
        get "behaviors"
        get "tags"
      end
    end 
    resources :tags, :defaults => { :format => 'json'} do
        collection do 
          get 'behaviors' 
        end
    end
    namespace :tasks, :defaults => { :format => 'json'}  do
        get 'schedule', :path => "/:id/schedule"
    end
  end

  post "sequences/json_to_cpp"
  post "sequences/create"
  resources :sequences

  post "schemes/create"
  resources :schemes

end

Applications/RailsApp/app/models/command.rb
class Command < ActiveRecord::Base
	belongs_to :user
	belongs_to :task
	validates_presence_of :task_id, :user_id, :code

	def code
		JSON.parse(self[:code])
	end
end

Applications/RailsApp/app/controllers/commands_controller.rb
class CommandsController < ApplicationController
  before_action :set_command, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /commands
  # GET /commands.json
  def index
    @commands = Command.all
  end

  # GET /commands/1
  # GET /commands/1.json
  def show
  end

  # GET /commands/new
  def new
    @command = Command.new
  end

  # GET /commands/1/edit
  def edit
  end

  # POST /commands
  # POST /commands.json
  def create
    @command = Command.new(command_params)

    respond_to do |format|
      if @command.save
        format.html { redirect_to @command, notice: 'Command was successfully created.' }
        format.json { render action: 'show', status: :created, location: @command }
      else
        format.html { render action: 'new' }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /commands/1
  # PATCH/PUT /commands/1.json
  def update
    respond_to do |format|
      if @command.update(command_params)
        format.html { redirect_to @command, notice: 'Command was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @command.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /commands/1
  # DELETE /commands/1.json
  def destroy
    @command.destroy
    respond_to do |format|
      format.html { redirect_to commands_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_command
      @command = Command.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def command_params
      params.require(:command).permit(:task_id, :user_id, :code)
    end
end

Applications/RailsApp/app/views/commands/_form.html.erb
<%= form_for(@command) do |f| %>
  <% if @command.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@command.errors.count, "error") %> prohibited this command from being saved:</h2>

      <ul>
      <% @command.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :task_id %><br>
   <%= select("command", "task_id", current_user.tasks.collect {|p| [ p.title, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= select("command", "user_id", User.all.collect {|p| [ p.email, p.id ] }) %>
  </div>
  <div class="field">
    <%= f.label :code %><br>
    <%= f.text_area :code %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

Applications/RailsApp/app/views/commands/edit.html.erb
<h1>Editing command</h1>

<%= render 'form' %>

<%= link_to 'Show', @command %> |
<%= link_to 'Back', commands_path %>

Applications/RailsApp/app/views/commands/index.html.erb
<h1>Listing commands</h1>

<table class="table">
  <thead>
    <tr>
      <th>Task</th>
      <th>User</th>
      <th>Code</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @commands.each do |command| %>
      <tr>
        <td><%= command.task_id %></td>
        <td><%= command.user_id %></td>
        <td><%= command.code %></td>
        <td><%= link_to 'Show', command %></td>
        <td><%= link_to 'Edit', edit_command_path(command) %></td>
        <td><%= link_to 'Destroy', command, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Command', new_command_path %>

Applications/RailsApp/app/views/commands/new.html.erb
<h1>New command</h1>

<%= render 'form' %>

<%= link_to 'Back', commands_path %>

Applications/RailsApp/app/views/commands/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Task:</strong>
  <%= @command.task.title %>
</p>

<p>
  <strong>User:</strong>
  <%= @command.user.email %>
</p>

<p>
  <strong>Code:</strong>
  <%= @command.code %>
</p>

<%= link_to 'Edit', edit_command_path(@command) %> |
<%= link_to 'Back', commands_path %>